In [15]:
import numpy as np
list_ =['1','2','3','4','5']
array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

#Q1

In [8]:
print("Data type of 'list_':" , type(list_))
print("Data type of 'array_list':" , type(array_list))

Data type of 'list_': <class 'list'>
Data type of 'array_list': <class 'numpy.ndarray'>


#Q2

In [19]:
print("Data type of 'element_list_':")
for elements in list_:
    print(type(elements))
    
print("\nData type of 'element_array_list':")
for elements in array_list:
    print(type(elements))

Data type of 'element_list_':
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of 'element_array_list':
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [14]:
array_list= np.array(object =list_ , dtype = int)
array_list

array([1, 2, 3, 4, 5])

#Q3

In [18]:
print("Data type of elements in 'list_':")
for elements in list_:
    print(type(elements))
    
print("\nData type of elements in 'array_list':")
for elements in array_list:
    print(type(elements))

Data type of elements in 'list_':
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in 'array_list':
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [20]:
num_list = [[ '1','2','3'],['4','5','6',]]
num_array = np.array(object = num_list)

#Q4

In [27]:
print(num_array.shape)
print(num_array.size)

(2, 3)
6


#Q5

In [30]:
zeros_array = np.zeros((3,3))
print("Array of zeros:")
print(zeros_array)

Array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [33]:
Identity_array = np.eye(5)
print("Array of Identity:")
print(Identity_array)

Array of Identity:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
